# Carefold — Healthcare AI Agent Marketplace & Runtime
# Copyright 2026 Spectrayan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Carefold constants package.

Centralizes API endpoints, status codes, SSE events, LLM defaults,
boundary thresholds, and filesystem paths.
"""

from carefold.constants import agents, api, defaults, extraction, models, paths
from carefold.constants.agents import (
    AGENT_BENEFITS_GUIDE,
    AGENT_DOCUMENT_EXTRACTOR,
    AGENT_HABIT_COMPANION,
    AGENT_ORCHESTRATOR,
    AGENT_TEMPLATE,
    AGENT_VISIT_STEWARD,
    DELEGATION_TOOLS,
    EXTRACTION_TOOLS,
)
from carefold.constants.api import (
    AGENTS_ENDPOINT,
    API_AGENTS,
    API_AUDIT,
    API_CHAT,
    API_HEALTH,
    API_PREFIX,
    API_SKILLS,
    API_V1_PREFIX,
    AUDIT_ENDPOINT,
    CHAT_ENDPOINT,
    EVENT_DONE,
    EVENT_MESSAGE,
    EVENT_REFUSAL,
    EVENT_SUGGESTIONS,
    EVENT_TEXT_DELTA,
    EVENT_TOKEN,
    EVENT_TOOL_END,
    EVENT_TOOL_START,
    HEALTH_ENDPOINT,
    HTTP_200_OK,
    HTTP_400_BAD_REQUEST,
    HTTP_403_FORBIDDEN,
    HTTP_404_NOT_FOUND,
    HTTP_500_INTERNAL_SERVER_ERROR,
    HTTP_BAD_REQUEST,
    HTTP_FORBIDDEN,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_NOT_FOUND,
    HTTP_OK,
    SKILLS_ENDPOINT,
    SSE_EVENT_DONE,
    SSE_EVENT_ERROR,
    SSE_EVENT_MESSAGE,
    SSE_EVENT_REFUSAL,
    SSE_EVENT_SUGGESTIONS,
    SSE_EVENT_TEXT_DELTA,
    SSE_EVENT_TOKEN,
    SSE_EVENT_TOOL_END,
    SSE_EVENT_TOOL_START,
    SSE_HEADERS,
    SSE_MEDIA_TYPE,
)
from carefold.constants.defaults import (
    ALLOWED_ATTACHMENT_EXTENSIONS,
    ALLOWED_SKILL_DOC_EXTENSIONS,
    ALLOWED_TEXT_EXTENSIONS,
    BUNDLED_AGENT_IDS,
    BUNDLED_SKILL_IDS,
    DEFAULT_AUDIT_LIMIT,
    DEFAULT_CORS_ORIGINS,
    DEFAULT_FORBIDDEN_INTENTS,
    DEFAULT_MAX_REFLECTIONS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_PAGE_SIZE,
    FORBIDDEN_INTENT_PREFIX,
    MAX_ATTACHMENT_SIZE,
    MAX_FILE_SIZE_BYTES,
    MAX_FILE_SIZE_MB,
    MAX_REFLECTION_RETRIES,
    MAX_RETRIES,
    MAX_THREAD_HISTORY,
    MAX_TOOL_ITERATIONS,
    MAX_TOOL_OUTPUT_CHARS,
    PHASE_0_TOOLS,
    SQLITE_BUSY_TIMEOUT_MS,
    SQLITE_CONNECT_TIMEOUT_SECONDS,
    SQLITE_JOURNAL_MODE,
)
from carefold.constants.models import (
    DEFAULT_MODEL,
    DEFAULT_MODELS,
    DEFAULT_OLLAMA_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_TIMEOUT,
    DEFAULT_TIMEOUT_SECONDS,
    PROVIDER_ALIASES,
    PROVIDER_ANTHROPIC,
    PROVIDER_CUSTOM,
    PROVIDER_GOOGLE,
    PROVIDER_MOCK,
    PROVIDER_OLLAMA,
    PROVIDER_OPENAI,
    SUPPORTED_PROVIDERS,
)
from carefold.constants.paths import (
    AGENTS_DIR,
    ATTACHMENTS_DIR,
    AUDIT_LOG_FILENAME,
    CAREFOLD_HOME,
    CHATS_DIR,
    DEFAULT_AUDIT_LOG,
    DEFAULT_DB_PATH,
    DEFAULT_HOME_DIR,
    DEFAULT_WORKSPACE_ROOT,
    ENV_HOME_DIR,
    LOGS_DIR,
    NOTES_DIR,
    REFERENCES_DIR,
    RESOURCES_DIR,
    SKILLS_DIR,
    SQLITE_DB_FILENAME,
    UPLOADS_DIR,
    WORKSPACE_DIR,
    WORKSPACE_NOTES_DIR,
)

__all__ = [
    "agents",
    "api",
    "defaults",
    "extraction",
    "models",
    "paths",
    # Agents
    "AGENT_ORCHESTRATOR",
    "AGENT_DOCUMENT_EXTRACTOR",
    "AGENT_VISIT_STEWARD",
    "AGENT_BENEFITS_GUIDE",
    "AGENT_HABIT_COMPANION",
    "AGENT_TEMPLATE",
    "DELEGATION_TOOLS",
    "EXTRACTION_TOOLS",
    # Re-exported key constants for direct access from carefold.constants
    "API_PREFIX",
    "API_V1_PREFIX",
    "HEALTH_ENDPOINT",
    "CHAT_ENDPOINT",
    "AGENTS_ENDPOINT",
    "SKILLS_ENDPOINT",
    "AUDIT_ENDPOINT",
    "HTTP_OK",
    "HTTP_NOT_FOUND",
    "HTTP_BAD_REQUEST",
    "HTTP_FORBIDDEN",
    "HTTP_INTERNAL_SERVER_ERROR",
    "SSE_EVENT_TOKEN",
    "SSE_EVENT_TEXT_DELTA",
    "SSE_EVENT_DONE",
    "SUPPORTED_PROVIDERS",
    "DEFAULT_MODEL",
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TEMPERATURE",
    "MAX_FILE_SIZE_BYTES",
    "MAX_ATTACHMENT_SIZE",
    "MAX_RETRIES",
    "MAX_REFLECTION_RETRIES",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_AUDIT_LIMIT",
    "MAX_TOOL_ITERATIONS",
    "MAX_TOOL_OUTPUT_CHARS",
    "MAX_THREAD_HISTORY",
    "DEFAULT_WORKSPACE_ROOT",
    "DEFAULT_HOME_DIR",
    "UPLOADS_DIR",
    "ENV_HOME_DIR",
    "CAREFOLD_HOME",
    "WORKSPACE_DIR",
    "RESOURCES_DIR",
    "ATTACHMENTS_DIR",
    "AUDIT_LOG_FILENAME",
    "DEFAULT_AUDIT_LOG",
    "SQLITE_DB_FILENAME",
    "DEFAULT_DB_PATH",
    "FORBIDDEN_INTENT_PREFIX",
    "DEFAULT_FORBIDDEN_INTENTS",
]
